### ISSUE TITLE
TOD link dead

### ISSUE THREAD

**Issue by NguyenRichard** [evinpinar/supergb-d#1]
Hello,

We are currently trying to find an algorithm that segments objects without necessarily giving the class labels using RGB-D data from HoloLens 2 and found your project which seems to fit perfectly.

Following the steps on the Readme, we couldn't have access to the datasets TOD and TOD-Z to train the model.

Apart from the access to the dataset for training from scratch, is it possible for you to make available a pretrained model to try some inference using our own images?

Best regards,
Richard.

**Comment by evinpinar** [comment]
Thanks a lot for your interest! I have updated the placeholder links with the working links now, also provided a trained checkpoint which runs with 128 superpixel patches, and without DINO features (so only rgb, depth and normals). Please see ReadMe for the links.
